# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cf5a4f27d7339d64755b005d559031e3bc9e52c069cd6b116f80c0891fd8832a8302e2788d8eb4a10220bea72bb330e268478520f00b2d836217a44c38039a5

test:
  secret_key_base: 66408fea188fe1b40542c3bed3543c57891358d6b663d3b03d95d75ba3b56ce1cc5dde227d971edb3ff71275773c8c40d2c91611717b95ae9a32c9a163afa106

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
